"""empty message

Revision ID: c335aef6d4b2
Revises: 88c3864f97aa
Create Date: 2026-10-01 12:33:25.810935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c335aef6d4b2'
down_revision = '88c3864f97aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_foto', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('caminho_foto')

    # ### end Alembic commands ###
